name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, run tests
      run: |
        npm install --save-dev coveralls @babel/preset-env babel-jest esm jest
        npm test
    - name: Coveralls
      uses: coverallsapp/github-action@main
      env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@main

      