name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install, run tests
      run: |
        npm install --save-dev coveralls @babel/preset-env babel-jest esm jest
        npm test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      